spring.application.name=n1h5-models-backend

# 1. Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/n1h5_db
spring.datasource.username=hieunho500
spring.datasource.password=0362476791
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình JPA / Hibernate 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Cấu hình Swagger UI 
springdoc.swagger-ui.path=/swagger-ui.html

# 4. Cấu hình JWT
jwt.secret=dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXRrZXlmb3Jqd3RhdXRoZW50aWNhdGlvbnByb2plY3QxMjM0NTY=
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# 5. Cấu hình redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 6. Cau hinh cloudinary
cloudinary.cloud-name=gkmujgkk
cloudinary.api-key=851944821478176
cloudinary.api-secret=erNAAiq24Jago6D9aIP2wPxGaT0