spring.application.name=n1h5-models-backend

# 1. Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/n1h5_db
spring.datasource.username=hieunho500
spring.datasource.password=0362476791
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình JPA / Hibernate 
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# 3. Cấu hình Swagger UI 
springdoc.swagger-ui.path=/swagger-ui.html